//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakipYonetim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categories> categories { get; set; }
        public DbSet<projects> projects { get; set; }
        public DbSet<projectTask> projectTask { get; set; }
        public DbSet<projectUsers> projectUsers { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<userLog> userLog { get; set; }
        public DbSet<users> users { get; set; }
    }
}
