//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakipYonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projects
    {
        public projects()
        {
            this.projectTask = new HashSet<projectTask>();
            this.projectUsers = new HashSet<projectUsers>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string iconHref { get; set; }
        public string description { get; set; }
        public Nullable<int> progress { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<System.DateTime> lastChangeDate { get; set; }
        public Nullable<int> systemUserID { get; set; }
    
        public virtual categories categories { get; set; }
        public virtual ICollection<projectTask> projectTask { get; set; }
        public virtual ICollection<projectUsers> projectUsers { get; set; }
    }
}
