//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakipYonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectUsers
    {
        public int ID { get; set; }
        public int userID { get; set; }
        public int projectID { get; set; }
        public System.DateTime createdDate { get; set; }
    
        public virtual projects projects { get; set; }
        public virtual users users { get; set; }
    }
}
