//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakipYonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.projectTask = new HashSet<projectTask>();
            this.projectUsers = new HashSet<projectUsers>();
            this.userLog = new HashSet<userLog>();
        }
    
        public int ID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string confirmPass { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string email { get; set; }
        public Nullable<int> roleID { get; set; }
    
        public virtual ICollection<projectTask> projectTask { get; set; }
        public virtual ICollection<projectUsers> projectUsers { get; set; }
        public virtual roles roles { get; set; }
        public virtual ICollection<userLog> userLog { get; set; }
    }
}
