//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakipYonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userLog
    {
        public int ID { get; set; }
        public Nullable<int> userID { get; set; }
        public string ipAdress { get; set; }
        public Nullable<System.DateTime> systemRecordTime { get; set; }
    
        public virtual users users { get; set; }
    }
}
